### ISSUE TITLE
Is the AppImage available for download?

### ISSUE THREAD

**Issue by probonopd** [wxMaxima-developers/docker-wxmaxima#1]
Thanks for making an AppImage.
Is the AppImage available for download somewhere?

**Comment by lokedhs** [comment]
The current test versions can be found at https://loke.keybase.pub/wxmaxima-x86_64.AppImage. There are still some issues with it, so it might not run correctly.

**Comment by probonopd** [comment]
Indeed. Some needed libraries are missing in the bundle, leading to the error shown in https://github.com/AppImage/appimage.github.io/pull/1216. Please let me know if you need help how to fix this (e.g., using linuxdeployqt).

**Comment by lokedhs** [comment]
I've updated the build to include libpng. This version also fixes some other problems that can occur if you already have a version of Maxina installed.

Please try it and let me know if it works.

**Comment by probonopd** [comment]
Has the download link changed?

**Comment by lokedhs** [comment]
No. It's still the same url.

**Comment by probonopd** [comment]
Thank you, I got a 404 but it looks like this was an intermittent issue.

**Comment by probonopd** [comment]
Now getting

![](https://github.com/AppImage/appimage.github.io/blob/e2ef23232a120d3677244566639591f65da2db8e/database/wxMaxima/screenshot.png?raw=true)

Please see https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#libstdcso6.

**Comment by lokedhs** [comment]
What distribution are you using?

**Comment by probonopd** [comment]
The oldest still-supported Ubuntu LTS release, which currently is Ubuntu 14.04 (trusty). This is the minimum requirement to be listed on https://appimage.github.io/.

**Comment by lokedhs** [comment]
The application would been to be recompiled against an older C++ library. I
need to check if its feasible.

I won't have time to do that in the next few days, but you're welcome to
try as well. It might be as easy as specifying an older Debian release in
the dockerfile.

**Comment by probonopd** [comment]
No hurries. Thanks!

**Comment by lokedhs** [comment]
I've now built the binary with the oldest Debian that I could find. Please let me know if it works now.

**Comment by probonopd** [comment]
Thank you. 

This time

![](https://raw.githubusercontent.com/AppImage/appimage.github.io/4766d090939b1b9fbccbb2cbc634c13c47c7f925/database/wxMaxima/screenshot.png)

Please consider to build on Ubuntu 14.04 trusty using Travis CI rather than some local machine.

**Comment by lokedhs** [comment]
The build is done using docker in order to make it consistent.

Please try to install GTK 3 on your system. This should make it work properly.

**Comment by probonopd** [comment]
It is a key concept of AppImage that it needs to run on the target systems without the user needing to install anything. Can you please build in a Ubuntu 14.04 container? That will solve it immediately. Thanks.

**Comment by lokedhs** [comment]
I did. But I install GTK 3 in the container before building. Otherwise I have to build GTK 3 with all dependencies and bundle it together inside the appimage. That's too much.

**Comment by probonopd** [comment]
> I install GTK 3 in the container before building.

That's entirely OK, if the system is no newer than the oldest still-supported LTS release of Ubuntu, which currently is 14.04... can you compile it there instead on Debian?

**Comment by gunterkoenigsmann** [comment]
Sorry that it took me so long to find out how to do it. But from now on all releases should automagically appear here: https://github.com/wxMaxima-developers/docker-wxmaxima/releases

**Comment by probonopd** [comment]
Thank you :+1:
