### ISSUE TITLE
Assets missing

### ISSUE THREAD

**Issue by paveloom** [wxMaxima-developers/docker-wxmaxima#6]
There are no AppImages for the latest two releases (`22.09.0-0` and `22.09.0-1`).

**Comment by gunterkoenigsmann** [comment]
That unfortunately is true: GitHub actions automatically generates one, but the GitHub action that is supposed to upload the result is currently broken and unmaintained.

**Comment by paveloom** [comment]
You can try https://github.com/softprops/action-gh-release, this one has been working fine for me.

**Comment by gunterkoenigsmann** [comment]
With that action I get:

````

compile
Failed to upload release asset wxmaxima-x86_64.AppImage. received status code 422
Validation Failed
[{"resource":"ReleaseAsset","code":"custom","field":"size","message":"size must be greater than or equal to 1"}]
````
Do you have an idea what I am doing wrong?

**Comment by paveloom** [comment]
Seems like something wrong with the AppImage. Was it built? The log of the build step contains an error in the end. I would recommend uploading the result as an [artifact](https://github.com/actions/upload-artifact), so you can test it.

Also, seems like the option `append_body` doesn't exist in the [`v1`](https://github.com/softprops/action-gh-release/tree/v1) version of the action. You might want to switch to master (via `@master`) if you want to use it.

Try with smaller files first (like a dummy text file), so you don't have to wait 20 minutes each try. Then check if the AppImage build is all right via the `upload-artifact` action.

Also, this is most likely not a good way to copy a binary:

https://github.com/wxMaxima-developers/docker-wxmaxima/blob/9cb8c43576b4d837d5c69f8045fb12600051c872/build_appimage.sh#L3

Perhaps, calling [`docker cp`](https://docs.docker.com/engine/reference/commandline/cp) would be enough ([create](https://docs.docker.com/engine/reference/commandline/create) a temporary container for that).

**Comment by gunterkoenigsmann** [comment]
With your help this issue should be resolved now. Thanks a lot!
